#!/bin/bash

dir=${PWD}
git clone https://github.com/bakkeby/dmenu-flexipatch.git $dir/src
ln -sf $dir/config.h $dir/src/config.h
ln -sf $dir/patches.h $dir/src/patches.h
# ln -sf $dir/config.mk $dir/flexpath/config.mk
